#=========================================================================
# TravisCI Setup
#=========================================================================
# force travis build

#------------------------------------------------------------------------
# language and build matrix
#------------------------------------------------------------------------

language: c

#------------------------------------------------------------------------
# install dependencies
#------------------------------------------------------------------------

install:
 - cd $HOME
 - wget https://github.com/cornell-brg/verilator-travisci-cache/raw/master/verilator-travis-4.008.tar.gz
 - tar -xvf verilator-travis-4.026.tar.gz
 - export VERILATOR_ROOT=$HOME/verilator
 - export PATH=$VERILATOR_ROOT/bin:$PATH
 - which verilator
 - verilator --version

#------------------------------------------------------------------------
# test runner
#------------------------------------------------------------------------

script:
 - echo "done"


